version: '3.8'

services:
  dualme-virtual-tryon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dualme-tryon
    ports:
      - "7860:7860"
      - "8000:8000"  # Health check endpoint
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./ckpts:/workspace/ckpts
      - ./data:/workspace/data
      - ./logs:/workspace/logs
      - dualme_cache:/workspace/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  dualme_cache:
    driver: local 